repos:
  - repo: https://github.com/LiquidFun/aoc_tiles
    rev: 0.4.0
    hooks:
      - id: aoc-tiles
        args: 
          - --language-sorting=rs,jl,kt,py
          - --exclude-patterns="2021/*/*.apl,2021/*/*.py,2021/*/*.cpp"

