repos:
  - repo: https://github.com/LiquidFun/aoc_tiles
    rev: 0.5.0
    hooks:
      - id: aoc-tiles
        args: 
          - --language-sorting=jl,kt,py,rs
          - --exclude-patterns="2021/*/*.apl,2021/*/*.py,2021/*/*.cpp"
          - --auto-add-tiles-to-git=amend

